/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FilesTable: typeof import('./components/Operations/FilesTable.vue')['default']
    HandlerMenu: typeof import('./components/HandlerMenu.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Operations: typeof import('./components/Operations.vue')['default']
    OperationWrapper: typeof import('./components/OperationWrapper.vue')['default']
  }
}
