/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionContainer: typeof import('./components/Operations/Action/ActionContainer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileFilter: typeof import('./components/Operations/Filter/FileFilter.vue')['default']
    FileFilterSelector: typeof import('./components/Operations/Filter/FileFilterSelector.vue')['default']
    FilesTable: typeof import('./components/Operations/TableView/FilesTable.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HandlerContainer: typeof import('./components/Operations/Handlers/HandlerContainer.vue')['default']
    HandlerMenu: typeof import('./components/HandlerMenu.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Operations: typeof import('./components/Operations/Operations.vue')['default']
    OperationWrapper: typeof import('./components/Operations/OperationWrapper.vue')['default']
  }
}
